version: "3"

tasks:

  # Internal tasks

  install-python:
    internal: true
    cmds:
      - pip install -r requirements_dev.txt

  install-ha:
    internal: true
    dir: homeassistant-frontend
    cmds:
      - yarn install
    sources:
      - package.json
      - yarn.lock
    status:
      - test -d node_modules

  install:
    internal: true
    cmds:
      - yarn install
    sources:
      - package.json
      - yarn.lock
    status:
      - test -d node_modules

  clean:
    internal: true
    cmds:
      - rm -rf dist/

  rollup:
    internal: true
    cmds:
      - ./node_modules/rollup/dist/bin/rollup -c --bundleConfigAsCjs

  update-submodule:
    internal: true
    cmds:
      - rm -R homeassistant-frontend
      - rm -R rounded-theme
      - git submodule update --init --recursive --remote

  # Exposed tasks

  bootstrap:
    cmds:
      - task: update-submodule
      - task: install-python
      - task: install-ha
      - task: install

  build:
    deps: [install, install-ha, install-python]
    cmds:
      - task: clean
      - task: rollup

  start-dev:
    deps: [install, install-python]
    cmds:
      - ./node_modules/rollup/dist/bin/rollup -c --watch --bundleConfigAsCjs

  start-hassio:
    deps: [install-python]
    cmds:
      - mkdir -p .hass_dev/themes/
      - cp rounded-theme/themes/* .hass_dev/themes/
      - hass -c .hass_dev/ --debug